
services:
  web:
    build: .
    command: gunicorn bookstore.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"  # Exposed internally for Nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose to browser
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static  # Mount your collected static files
    depends_on:
      - web
